In [ ]:

#given values for the problems

#d = np.array([[0,2,30,9,1]
 #         ,[4,0,47,7,7]
  #        ,[31,33,0,33,36]
   #       ,[20,13,16,0,28]
    #      ,[9,36,22,22,0]])
#E = int(input()) 
#d = np.array([[int(j) for j in input().split()] for i in range(E)])

import numpy as np
import sys

#n = 
d = np.matrix([])
d = np.loadtxt('test.txt') #[[int(j) for j in input().split()] for i in range(n)] #np.random.randint(1, 50, size=(20, 20))
print(np.matrix(d))


iteration = 700
n_ants = 20
n_citys = 5 #int(E)

# intialization part

m = n_ants
n = n_citys
e = 1.5         #evaporation rate
alpha = 1     #pheromone factor
beta = 3       #visibility factor

#calculating the visibility

visibility = 1/d
visibility[visibility == np.inf ] = 0

#intializing pheromne present 

pheromne = .1*np.ones((m,n))

#intializing the rute
#note adding 1 

rute = np.ones((m,n+1))

for ite in range(iteration):
    
    rute[:,0] = 1         
    #initial starting and ending 
    
    for i in range(m):
        
        temp_visibility = np.array(visibility)         
        #creating a copy of visibility
        
        for j in range(n-1):
            #print(rute)
            
            combine_feature = np.zeros(5)     #intializing combine_feature array 
            cum_prob = np.zeros(5)            #intializing cummulative probability 
            
            cur_loc = int(rute[i,j]-1)        #current city of the ant
            
            temp_visibility[:,cur_loc] = 0     #making visibility of the current
            
            p_feature = np.power(pheromne[cur_loc,:],beta)         #calculating pheromne feature 
            v_feature = np.power(temp_visibility[cur_loc,:],alpha)  #calculating visibility feature
            
            p_feature = p_feature[:,np.newaxis]                     #adding axis to make a size[5,1]
            v_feature = v_feature[:,np.newaxis]                     #adding axis to make a size[5,1]
            
            combine_feature = np.multiply(p_feature,v_feature)     #calculating the combine feature
                        
            total = np.sum(combine_feature)                        #sum of all the feature
            
            probs = combine_feature/total   #finding probability of element
            
            cum_prob = np.cumsum(probs)     #calculating cummulative sum
            #print(cum_prob)
            r = np.random.random_sample()   #randon no in [0,1)
            #print(r)
            city = np.nonzero(cum_prob>r)[0][0]+1       #finding the next city 
            #print(city)
            
            rute[i,j+1] = city              #adding city to route 
           
        left = list(set([i for i in range(1,n+1)])-set(rute[i,:-2]))[0]     #finding the last untraversed city
        
        rute[i,-2] = left                   #adding untraversed city to route
       
    rute_opt = np.array(rute)               #intializing optimal route
    
    dist_cost = np.zeros((m,1))             #intializing total_distance_of_tour 
    
    for i in range(m):
        
        s = 0
        for j in range(n-1):
            
            s = s + d[int(rute_opt[i,j])-1,int(rute_opt[i,j+1])-1]   #calcualting total tour distance
        
        dist_cost[i]=s                      #storing distance of tour 
       
    dist_min_loc = np.argmin(dist_cost)             #finding location of minimum of dist_cost
    dist_min_cost = dist_cost[dist_min_loc]         
    #finging min of dist_cost
    
    best_route = rute[dist_min_loc,:]               #intializing current traversed as best
    pheromne = (1-e)*pheromne                       #evaporation of pheromne with (1-e)
    
    for i in range(m):
        for j in range(n-1):
            dt = 1/dist_cost[i]
            pheromne[int(rute_opt[i,j])-1,int(rute_opt[i,j+1])-1] = pheromne[int(rute_opt[i,j])-1,int(rute_opt[i,j+1])-1] + dt   
          
print(int(dist_min_cost[0]) + d[int(best_route[-2])-1,0])


[[ 0.  2. 30.  9.  1.]
 [ 4.  0. 47.  7.  7.]
 [31. 33.  0. 33. 36.]
 [20. 13. 16.  0. 28.]
 [ 9. 36. 22. 22.  0.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:25: RuntimeWarning: divide by zero encountered in true_divide


73.0
